[package]
name = "scraper"
version = "0.1.0"
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.101"
reqwest = { version = "0.11.4", features = ["json"] }
tokio = { version = "1.11.0", features = ["full"] }

